// =============================================================================
// pstast_core_config.h
// Foundational Execution Safety Module for the PSTAS Framework
//
// DANIEL ACOURT REVIEW NOTES:
// This header establishes the core, non-negotiable safety parameters for the
// Provably Safe, Trust-Aware System (PSTAS). Its purpose is to enforce
// deterministic behavior and provide a single source of truth for all
// safety-critical validation checks. Adherence to these constants is mandatory
// for all execution tiers.
//
// Generated by: PSTAS Executor (Jules, Tier 3)
// Version: 1.0.0
// Timestamp: 2025-12-02 20:50:21
// =============================================================================

#pragma once

#include <cstdint> // Required for fixed-width integer types if needed later.

// Namespace for all PSTAS core functionalities to prevent global scope pollution.
namespace PSTAS_Core
{
    // =========================================================================
    // SECTION 1: DETERMINISTIC SAFETY CONSTANTS
    // These values are declared `constexpr` to guarantee they are compile-time
    // constants, eliminating any possibility of runtime modification. This is
    // a cornerstone of the PSTAS deterministic safety substrate.
    // =========================================================================

    /**
     * @brief The mandatory minimum "Percentage of Truth" required for an
     * operation to be considered safe. Any measurement of trust or factual
     * accuracy (TAV Score) falling below this value constitutes a critical
     * safety violation.
     */
    constexpr double TAV_THRESHOLD = 0.950000;

    // =========================================================================
    // SECTION 2: PNDF VALIDATION FUNCTION
    // This function is the primary hook for pre-execution safety validation as
    // mandated by the PSTAS-MP-V3 Master Prompt.
    // =========================================================================

    /**
     * @brief Implements the mandatory PSTAS safety predicate (PNDF Standard Check).
     * @param measured_WCET The Worst-Case Execution Time measured during a task.
     * @param nominal_WCET The pre-calculated, approved WCET for the task.
     * @param measured_TAV The measured Trust-Aware Validation (TAV) score.
     * @param TAV_Check_Threshold The TAV threshold to check against (typically TAV_THRESHOLD).
     * @return bool - TRUE if a violation is detected, FALSE if the operation is compliant.
     */
    inline bool run_pndf_check(double measured_WCET, double nominal_WCET, double measured_TAV, double TAV_Check_Threshold)
    {
        // SAFETY PREDICATE LOGIC:
        // A violation occurs IF the measured execution time exceeds the approved nominal time
        // OR IF the measured trust score falls below the mandatory safety threshold.
        if ((measured_WCET > nominal_WCET) || (measured_TAV < TAV_Check_Threshold))
        {
            return true; // VIOLATION DETECTED
        }

        return false; // COMPLIANCE CONFIRMED
    }

} // namespace PSTAS_Core
